trigger:
- main
- bindu-dev

pool:
  name: Default

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - script: mvn package

    - script: | 
        mkdir -p build_output
        mv target/*.jar target/app.jar
        cp target/app.jar build_output/
        cd build_output
        zip -r app.zip app.jar

  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build_output/app.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: deploy 
  jobs:
  - job: deployjob
    steps:
     - task: DownloadBuildArtifacts@1
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         downloadPath: '$(System.ArtifactsDirectory)'

     - task: AzureRmWebAppDeployment@5
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'resourcegroup'
         appType: 'webApp'
         WebAppName: 'sdfregx-linux'
         packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'


     - task: AzureCLI@2
       inputs:
         azureSubscription: 'resourcegroup'
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: |
           az webapp config set \
           --name sdfregx-linux \
           --resource-group webapptest \
           --startup-file "java -jar /home/site/wwwroot/app.jar"
