trigger:
- main
- bindu-dev

pool:
  name: Default

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - script: mvn clean package

    - script: | 
        mkdir -p build_output
        mv target/*.jar target/app.jar
        cp target/app.jar build_output/
        cd build_output
        zip -r app.zip app.jar  

  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build_output/app.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - script: echo '$(Build.SourceBranch)'
      displayName: displaythe source

- stage: deploytodev
  dependsOn: build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/bindu-dev'))
  jobs:
  - job: deploydevjob
    steps:
     - task: DownloadBuildArtifacts@1
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         downloadPath: '$(System.ArtifactsDirectory)'

     - task: AzureRmWebAppDeployment@5
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'resourcegroup'
         appType: 'webApp'
         WebAppName: 'webappedfsdf-dev'
         packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'


     - task: AzureCLI@2
       inputs:
         azureSubscription: 'resourcegroup'
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: |
           az webapp config set \
           --name webappedfsdf-dev \
           --resource-group webapptest \
           --startup-file "java -jar /home/site/wwwroot/app.jar"

- stage: deploytoprod
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:

  - job: approvaljob
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: |
          424bindu@gmail.com    
        
  - job: deployprodjob
    steps:
     - task: DownloadBuildArtifacts@1
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         downloadPath: '$(System.ArtifactsDirectory)'

     - task: AzureRmWebAppDeployment@5
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'resourcegroup'
         appType: 'webApp'
         WebAppName: 'sdfregx-linux'
         packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'


     - task: AzureCLI@2
       inputs:
         azureSubscription: 'resourcegroup'
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: |
           az webapp config set \
           --name sdfregx-linux \
           --resource-group webapptest \
           --startup-file "java -jar /home/site/wwwroot/app.jar"

