trigger:
- main

pool:
  name: Default

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - script: mvn package

    - script: | 
        mkdir -p build_output
        mv target/*.jar target/app.jar
        cp target/app.jar build_output/
        cd build_output
        zip -r app.zip app.jar

  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build_output/app.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: deploy 
  jobs:
  - job: deployjob
    steps:
     - task: DownloadBuildArtifacts@1
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         downloadPath: '$(System.ArtifactsDirectory)'

     - task: AzureRmWebAppDeployment@5
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'resourcegroup'
         appType: 'webApp'
         WebAppName: 'sdfregx'
         packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'


     - task: AzureAppServiceSettings@1
       inputs:
         azureSubscription: 'resourcegroup'
         appName: 'sdfregx'
         resourceGroupName: 'webapptest'
         appSettings: |
           [
             {
            "name": "WEBSITE_STARTUP_FILE",
            "value": "java -jar /home/site/wwwroot/app.jar",
            "slotSetting": false
             }
       
           ] 